### ISSUE TITLE
Not working on forms

### ISSUE THREAD

**Issue by repli2dev** [vojtech-dobes/nette.ajax.js#134] opened 2016-10-19 09:42 UTC
We accidentally updated from 2.1 to 2.2 and encountered complete malfunction of AJAX request... The callbacks were attached but when triggering on form (by clicking on button) we get:

```
too much recursion (nette.ajax.js code on line 47)
Funkci getElementById() předán prázdný řetězec. (jQuery code)
too much recursion (jQuery code)
```

First stack trace:

```
nette/inner.fire()
scripts.all.js:52
nette/this.ajax/settings.beforeSend()
scripts.all.js:227
.ajax()
scripts.all.js:4
nette/this.ajax()
scripts.all.js:237
nette/inner.requestHandler()
scripts.all.js:60
n.event.dispatch()
scripts.all.js:3
n.event.add/r.handle()
scripts.all.js:3
n.event.trigger()
scripts.all.js:3
.triggerHandler()
scripts.all.js:3
.before()
scripts.all.js:330
nette/inner.fire/<()
scripts.all.js:54
.each()
scripts.all.js:2
nette/inner.fire()
scripts.all.js:52
nette/this.ajax/settings.beforeSend()
scripts.all.js:227
.ajax()
scripts.all.js:4
nette/this.ajax()
scripts.all.js:237
nette/inner.requestHandler()
scripts.all.js:60
n.event.dispatch()
scripts.all.js:3
n.event.add/r.handle()
scripts.all.js:3
n.event.trigger()
scripts.all.js:3
.triggerHandler()
scripts.all.js:3
.before()
scripts.all.js:330
nette/inner.fire/<()
scripts.all.js:54
.each()
scripts.all.js:2
nette/inner.fire()
scripts.all.js:52
nette/this.ajax/settings.beforeSend()
scripts.all.js:227
.ajax()
scripts.all.js:4
nette/this.ajax()
scripts.all.js:237
nette/inner.requestHandler()
scripts.all.js:60
n.event.dispatch()
scripts.all.js:3
n.event.add/r.handle()
scripts.all.js:3
n.event.trigger()
scripts.all.js:3
.triggerHandler()
scripts.all.js:3
.before()
scripts.all.js:330
nette/inner.fire/<()
scripts.all.js:54
.each()
scripts.all.js:2
nette/inner.fire()
scripts.all.js:52
nette/this.ajax/settings.beforeSend()
scripts.all.js:227
.ajax()
scripts.all.js:4
nette/this.ajax()
scripts.all.js:237
nette/inner.requestHandler()
scripts.all.js:60
n.event.dispatch()
scripts.all.js:3
n.event.add/r.handle()
scripts.all.js:3
n.event.trigger()
scripts.all.js:3
.triggerHandler()
scripts.all.js:3
.before()
scripts.all.js:330
nette/inner.fire/<()
scripts.all.js:54
.each()
scripts.all.js:2
nette/inner.fire()
scripts.all.js:52
nette/this.ajax/settings.beforeSend()
scripts.all.js:227
.ajax()
scripts.all.js:4
nette/this.ajax()
scripts.all.js:237
nette/inner.requestHandler()
scripts.all.js:60
n.event.dispatch()
scripts.all.js:3
n.event.add/r.handle()
scripts.all.js:3
n.event.trigger()
scripts.all.js:3
.triggerHandler()
```

Second stack trace:

```
n.event.dispatch()
scripts.all.js:3
n.event.add/r.handle()
scripts.all.js:3
n.event.trigger()
scripts.all.js:3
.triggerHandler()
scripts.all.js:3
.before()
scripts.all.js:330
nette/inner.fire/<()
scripts.all.js:54
.each()
scripts.all.js:2
nette/inner.fire()
scripts.all.js:52
nette/this.ajax/settings.beforeSend()
scripts.all.js:227
.ajax()
scripts.all.js:4
nette/this.ajax()
scripts.all.js:237
nette/inner.requestHandler()
scripts.all.js:60
n.event.dispatch()
scripts.all.js:3
n.event.add/r.handle()
scripts.all.js:3
n.event.trigger()
scripts.all.js:3
.triggerHandler()
scripts.all.js:3
.before()
scripts.all.js:330
nette/inner.fire/<()
scripts.all.js:54
.each()
scripts.all.js:2
nette/inner.fire()
scripts.all.js:52
nette/this.ajax/settings.beforeSend()
scripts.all.js:227
.ajax()
scripts.all.js:4
nette/this.ajax()
scripts.all.js:237
nette/inner.requestHandler()
scripts.all.js:60
n.event.dispatch()
scripts.all.js:3
n.event.add/r.handle()
scripts.all.js:3
n.event.trigger()
scripts.all.js:3
.triggerHandler()
scripts.all.js:3
.before()
scripts.all.js:330
nette/inner.fire/<()
scripts.all.js:54
.each()
scripts.all.js:2
nette/inner.fire()
scripts.all.js:52
nette/this.ajax/settings.beforeSend()
scripts.all.js:227
.ajax()
scripts.all.js:4
nette/this.ajax()
scripts.all.js:237
nette/inner.requestHandler()
scripts.all.js:60
n.event.dispatch()
scripts.all.js:3
n.event.add/r.handle()
scripts.all.js:3
n.event.trigger()
scripts.all.js:3
.triggerHandler()
scripts.all.js:3
.before()
scripts.all.js:330
nette/inner.fire/<()
scripts.all.js:54
.each()
scripts.all.js:2
nette/inner.fire()
scripts.all.js:52
nette/this.ajax/settings.beforeSend()
scripts.all.js:227
.ajax()
scripts.all.js:4
nette/this.ajax()
scripts.all.js:237
nette/inner.requestHandler()
scripts.all.js:60
n.event.dispatch()
scripts.all.js:3
n.event.add/r.handle()
scripts.all.js:3
n.event.trigger()
scripts.all.js:3
.triggerHandler()
scripts.all.js:3
.before()
scripts.all.js:330
nette/inner.fire/<()
scripts.all.js:54
.each()
scripts.all.js:2
nette/inner.fire()
scripts.all.js:52
nette/this.ajax/settings.beforeSend()
scripts.all.js:227
.ajax()
scripts.all.js:4
nette/this.ajax()
scripts.all.js:237
nette/inner.requestHandler()
scripts.all.js:60
n.event.dispatch()
scripts.all.js:3
n.event.add/r.handle()
scripts.all.js:3
n.event.trigger()
scripts.all.js:3
.triggerHandler()
scripts.all.js:3
.before()
scripts.all.js:330
nette/inner.fire/<()
scripts.all.js:54
.each()
scripts.all.js:2
nette/inner.fire()
scripts.all.js:52
nette/this.ajax/settings.beforeSend()
scripts.all.js:227
.ajax()
scripts.all.js:4
nette/this.ajax()
scripts.all.js:237
nette/inner.requestHandler()
scripts.all.js:60
n.event.dispatch()
scripts.all.js:3
n.event.add/r.handle()
scripts.all.js:3
n.event.trigger()
scripts.all.js:3
.triggerHandler()
scripts.all.js:3
.before()
scripts.all.js:330
nette/inner.fire/<()
scripts.all.js:54
.each()
scripts.all.js:2
nette/inner.fire()
scripts.all.js:52
nette/this.ajax/settings.beforeSend()
scripts.all.js:227
.ajax()
scripts.all.js:4
nette/this.ajax()
scripts.all.js:237
nette/inner.requestHandler()
scripts.all.js:60
n.event.dispatch()
scripts.all.js:3
n.event.add/r.handle()
scripts.all.js:3
n.event.trigger()
scripts.all.js:3
.triggerHandler()
scripts.all.js:3
.before()
scripts.all.js:330
nette/inner.fire/<()
scripts.all.js:54
.each()
scripts.all.js:2
nette/inner.fire()
scripts.all.js:52
nette/this.ajax/settings.beforeSend()
scripts.all.js:227
.ajax()
scripts.all.js:4
nette/this.ajax()
scripts.all.js:237
nette/inner.requestHandler()
scripts.all.js:60
n.event.dispatch()
scripts.all.js:3
n.event.add/r.handle()
scripts.all.js:3
n.event.trigger()
scripts.all.js:3
.triggerHandler()
scripts.all.js:3
.before()
scripts.all.js:330
nette/inner.fire/<()
scripts.all.js:54
.each()
scripts.all.js:2
nette/inner.fire()
scripts.all.js:52
nette/this.ajax/settings.beforeSend()
scripts.all.js:227
.ajax()
scripts.all.js:4
nette/this.ajax()
scripts.all.js:237
nette/inner.requestHandler()
scripts.all.js:60
n.event.dispatch()
scripts.all.js:3
n.event.add/r.handle()
scripts.all.js:3
n.event.trigger()
scripts.all.js:3
.triggerHandler()
scripts.all.js:3
.before()
scripts.all.js:330
nette/inner.fire/<()
scripts.all.js:54
.each()
scripts.all.js:2
nette/inner.fire()
scripts.all.js:52
nette/this.ajax/settings.beforeSend()
scripts.all.js:227
.ajax()
scripts.all.js:4
nette/this.ajax()
scripts.all.js:237
nette/inner.requestHandler()
scripts.all.js:60
n.event.dispatch()
scripts.all.js:3
n.event.add/r.handle()
scripts.all.js:3
n.event.trigger()
scripts.all.js:3
.triggerHandler()
scripts.all.js:3
.before()
scripts.all.js:330
nette/inner.fire/<()
scripts.all.js:54
.each()
scripts.all.js:2
nette/inner.fire()
```

**Comment by PingusPepan** [comment] 2016-10-20 22:36
I believe it was caused by update of nette.ajax.js to version 2.2.0 which was released recently.
Can you try #135 and see if it works and fixes the issue?

**Comment by senasi** [comment] 2016-10-21 12:26
Hello guys, we are experiencing same problems after upgrading from 2.1 to 2.2. 

Chrome dev tools:
```
Uncaught RangeError: Maximum call stack size exceeded
```

Firebug:
```
too much recursion
```

It's happening on several ajax calls in our project, but not on all of them. I don't have time to debug this more now, so we fixed it by downgrading back to 2.1.

**Comment by matoni555** [comment] 2016-10-23 08:36
Try to use latest version of netteForms.js
I think older version causes this error.

**Comment by repli2dev** [comment] 2016-12-09 13:36
@matoni555 We are not using netteForms.js in our project, so that should not be the source of problems (we are using live validation).

@PingusPepan this seems to solve the problems.

**Comment by romanmatyus** [comment] 2016-12-16 02:57
@PingusPepan solve the problem. ;)

**Comment by vojtech-dobes** [comment] 2017-02-23 20:59
Fix by @PingusPepan is merged now.

**Closed by vojtech-dobes** 2017-02-23 20:59 UTC
